# hosts/zenbook-s14/hardware.nix
{ lib, pkgs, ... }:
{
  services.asusd = {
    enable = true;
    enableUserService = true;
  };
  environment.systemPackages = [ pkgs.asusctl ];

  services.supergfxd.enable = lib.mkForce false;
  services.power-profiles-daemon.enable = true;
  services.thermald.enable = true;
}

/*
{ config, lib, pkgs, ... }:
{
  hardware.enableRedistributableFirmware = true;

  # Escolha UM: PPD (integra com asusd) ou TLP. Aqui: PPD.
  services.power-profiles-daemon.enable = true;

  hardware.enableAllFirmware = true;
  hardware.graphics = {
    enable = true;
    enable32Bit = true;          # 32-bit apps
    extraPackages = with pkgs; [ 
      intel-media-driver 
      # intel-vaapi-driver       # i965 — only for pre-Broadwell CPUs
      libvdpau-va-gl
        ];
  };
  environment.sessionVariables.LIBVA_DRIVER_NAME = "iHD";

  services.asusd = { enable = true; enableUserService = true; };
  services.thermald.enable = true;
  services.fwupd.enable = true;
  hardware.bluetooth.enable = true;
}


sudo cat /sys/kernel/debug/pmc_core/slp_s0_residency_usec   # should climb after suspend
sudo cat /sys/kernel/debug/pmc_core/package_cstate_show
nix shell nixpkgs#linuxPackages.turbostat  # then: sudo turbostat --quiet sleep 10

Do not add mem_sleep_default=deep. That advice is everywhere online, but modern Intel ultrabooks are frequently S0ix-only in firmware, and forcing S3 on a machine that doesn't support it can produce a laptop that suspends and never wakes. Check cat /sys/power/mem_sleep — if deep isn't listed, the option is meaningless anyway.
CPU_MAX_PERF_ON_BAT = 60. This is the one I'd most strongly push back on. Capping frequency usually hurts battery on modern Intel because of race-to-idle: finishing work fast and dropping into deep package C-states beats crawling at 60% for longer. Lunar Lake's efficiency story is heavily built on deep idle residency. You've already set CPU_ENERGY_PERF_POLICY_ON_BAT, which is the right lever — the hard cap is redundant and costs you responsiveness. I'd remove it and measur'

Battery charge limit. nixos-hardware exposes something like hardware.asus.battery.chargeUpto — I'm only moderately confident of that exact attribute name, so verify on search.nixos.org/options. Otherwise asusctl -c 80 works directly via asusd.

Hardware video decode — you already set intel-media-driver + LIBVA_DRIVER_NAME=iHD. Verify it's engaging with intel_gpu_top during playback; if it isn't, you're software-decoding and burning several watts.
Display refresh rate. If yours is the 120Hz OLED panel, dropping to 60Hz on battery is a measurable win.
powerManagement.powertop.enable = true; runs powertop --auto-tune at boot. It helps, but it aggressively enables USB autosuspend and can make peripherals (webcam, some mice, fingerprint readers) flaky. Test before committing.


I'll flag my confidence honestly: race-to-idle is well-established as a general principle, but I have no Lunar Lake-specific measurements to prove it holds on your chip. Test both ways with powertop before deciding.

CPU_ENERGY_PERF_POLICY_ON_BAT = "power" is the most aggressive setting. balance_power is the usual sweet spot.

PCIE_ASPM_ON_BAT = "powersupersave" is a known source of NVMe latency spikes and occasional I/O errors on some drives. If you see disk weirdness, drop to powersave.

{ config, pkgs, lib, ... }:
{
  # Escolha UM: PPD (integra com asusd) ou TLP. Aqui: PPD.
  services.power-profiles-daemon.enable = true;

  services.asusd = {
    enable = true;
    enableUserService = true;
  };

  services.thermald.enable = true;

  # powertop.enable roda --auto-tune no boot.
  # Pode quebrar webcam/leitor de digital. Ative só depois de testar.
  # powerManagement.powertop.enable = true;
}


/*{
    config,
}:
{

    
# https://github.com/NixOS/nixos-hardware/blob/master/asus/zenbook/um6702/default.nix

/*
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";  # check the current stable branch
    nixos-hardware.url = "github:NixOS/nixos-hardware/master";
  };

  outputs = { self, nixpkgs, nixos-hardware }: {
    nixosConfigurations.myhost = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        ./configuration.nix
        ./hardware-configuration.nix        # generated by nixos-generate-config

        nixos-hardware.nixosModules.common-cpu-intel
        nixos-hardware.nixosModules.common-pc-laptop
        nixos-hardware.nixosModules.common-pc-laptop-ssd
      ];
    };
  };
}
*/

